In [68]:
# Importad las librerías necesarias aquí
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from sklearn.linear_model import LogisticRegression


from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## Ejercicio 1 A: descarga el dataset de Iris de sklearn y transformalo en un dataframe de pandas

In [6]:
iris = datasets.load_iris()
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [10]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
data1.head(50)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
15                5.7               4.4                1.5               0.4   
16                5.4               3.9                1.3               0.4   
17                5.1               3.5                1.4               0.3   
18                5.7               3.8                1.7               0.3   
19                5.1               3.8                1.5               0.3   
20                5.4               3.4                1.7               0.2   
21                5.1               3.7                1.5               0.4   
22                4.6               3.6                1.0               0.2   
23                5.1               3.3                1.7               0.5   
24                4.8               3.4                1.9               0.2   
25                5.0               3.0                1.6               0.2   
26                5.0               3.4                1.6               0.4   
27                5.2               3.5                1.5               0.2   
28                5.2               3.4                1.4               0.2   
29                4.7               3.2                1.6               0.2   
30                4.8               3.1                1.6               0.2   
31                5.4               3.4                1.5               0.4   
32                5.2               4.1                1.5               0.1   
33                5.5               4.2                1.4               0.2   
34                4.9               3.1                1.5               0.2   
35                5.0               3.2                1.2               0.2   
36                5.5               3.5                1.3               0.2   
37                4.9               3.6                1.4               0.1   
38                4.4               3.0                1.3               0.2   
39                5.1               3.4                1.5               0.2   
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49  

## Ejercicio 1 B: Utiliza una técnica de reducción de dimensión (PCA) sobre las variables explicativas y visualiza los datos en 2 dimensiones. ¿ Qué visualización es la más adecuada para este caso concreto ?

In [22]:
a = data1.iloc[:,:-1]

In [20]:
X = data1[[x for x in data1.columns if x!='target']]
y = data1['target']

In [23]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [36]:
target_names = iris.target_names

pca = PCA(n_components=2)
X_train_r=pca.fit_transform(X_train)
X_test_r=pca.transform(X_test)

In [48]:
#X_train_r
y_train
df_pca = pd.DataFrame(X_train_r, columns=["pc1","pc2"])
df_pca["y_train"]=y_train.values
df_pca

pc1       pc2  y_train
0    3.829677  0.219859      2.0
1   -2.150407  0.946246      0.0
2   -2.686849  0.414629      0.0
3   -2.684287 -0.169526      0.0
4    0.016025 -0.680996      1.0
..        ...       ...      ...
100  1.474847 -0.128888      2.0
101  1.941866  0.060690      2.0
102  1.323975 -0.317661      1.0
103  2.354687  0.178675      2.0
104 -2.759798  0.360291      0.0

[105 rows x 3 columns]

In [46]:
y_train

118    2.0
18     0.0
4      0.0
45     0.0
59     1.0
      ... 
133    2.0
137    2.0
72     1.0
140    2.0
37     0.0
Name: target, Length: 105, dtype: float64

In [61]:
data= []
y_categories=np.sort(df_pca["y_train"].unique())
color_dict={0:"blue",1:"red",2:"yellow"}

for cat in y_categories:
    data.append(
        go.Scatter(
            x=df_pca[df_pca["y_train"]==cat]["pc1"],
            y=df_pca[df_pca["y_train"]==cat]["pc2"],
            mode= "markers", 
            name=cat,
            marker_color=color_dict[cat]
        ) 
    )

layout= go.Layout( title="PCA Iris", xaxis_title="PC1", yaxis_title="PC2")

fig = go.Figure(data = data, layout = layout)

fig.show()

In [55]:
y_categories=np.sort(df_pca["y_train"].unique())

In [59]:
y_categories=np.sort(y_categories)
y_categories

array([0., 1., 2.])

In [ ]:
go.Scatter(
        x=X_train_r[:,0],
        y=X_train_r[:,1],
        mode= "markers", 
        marker_color="blue")       


## Ejercicio 1 C: Construye un modelo de clasificación lineal. Evalúa las métricas más importantes. Crea una visualización para la matriz de confusión

In [65]:
y_train.value_counts()

2.0    37
0.0    36
1.0    32
Name: target, dtype: int64

In [67]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

accuracy_score(y_test, clf.predict(X_test))


0.9777777777777777

In [69]:
confusion_matrix(y_test, clf.predict(X_test))

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 13]], dtype=int64)

In [ ]:
train_prediction = clf.predict(X[:2, :])
array([0, 0])
clf.predict_proba(X[:2, :])
array([[9.8...e-01, 1.8...e-02, 1.4...e-08],
       [9.7...e-01, 2.8...e-02, ...e-08]])
clf.score(X, y)

## Ejercicio 1 D: ¿Cómo podrías visualizar las regiones de decisión del modelo anterior?

__Nota: La región de decisión de un modelo de clasificación consiste en los puntos del plano que se identifican con cada una de las categorías__ 

## Ejercicio 2 A: Descarga y lee el dataset contenido en el siguiente enlace. https://www.kaggle.com/camnugent/california-housing-prices

In [ ]:
df = pd.read_csv("../../Datos/housing.csv")
df.head()

## Ejercicio 2 B: Realiza un análisis exploratorio de los datos con los siguientes objetivos:

* Indica si hay o no valores desconocidos
* Realiza una visualización de la matriz de correlaciones
* Visualiza la relación que existe entre la proximidad al oceano con el precio mediano de la casa. ¿Indica que tipo de visualización quieres utilizar y por qué?
* ¿ Cómo afecta el número total de dormitorios al precio mediano de la casa ? Crea una gráfica que muestre la relación entre ambas variables

## Ejercicio 2 C: Construye un modelo de regresión usando árboles para predecir el precio mediano de la casa. ¿Cuáles son las variables más importantes del modelo? Monta una gráfica que lo muestre.

## Ejercicio 2 D: Evalúa el modelo anterior y saca las métricas más relevantes que consideres. ¿Qué interpretación puedes sacar del modelo anterior con todo lo recopilado?

## Ejercicio 3 A: Descarga y lee el csv de https://www.kaggle.com/harrywang/wine-dataset-for-clustering 

In [ ]:
df = pd.read_csv("../../Datos/wine-clustering.csv")
df.head()

## Ejercicio 3 B: Genera un modelo de clustering para agrupar los diferentes tipos de vinos

## Ejercicio 3 C: Evalúa el modelo de clustering usando dos métricas distintas

## Ejercicio 3 D: Visualiza, con técnicas de reducción de dimensión, cómo quedan distribuidos los clusters.

## Ejercicio 3 E: Extrae, a partir de visualizaciones, 3 características que diferencien un cluster de otro.

## Ejercicio 4 A: Descarga y lee el csv de Titanic de https://www.kaggle.com/cities/titanic123 (Puedes usar la librería Seaborn para leer este dataset sin necesidad de descargarlo)

## Ejercicio 4 B: Realiza una gráfica para sacar la siguiente información:

* ¿Cuál es la distribución de las edades de las mujeres que fallecieron en el barco?
* ¿En qué proporción sobrevivieron los hombres, mujeres del barco?
* ¿El barco priorizó salvar alguna clase (primera, segunda o tercera) en particular?
* ¿Existe alguna franja de edad que se priorizara para salvarse?

__Justifica por qué usas estas visualizaciones y realízalo todo en una única gráfica__