# Estructuras para agrupar datos

Hasta ahora hemos visto los diferentes tipos de datos, números, fechas, booleanos, cadenas y como operar con ellos. Ahora vamos a ver las estructuras más simples para agrupar tipos de datos. La documentación general para estas estructuras las tenemos aquí. https://docs.python.org/3/tutorial/datastructures.html

## Tuplas

Las tuplas son estructuras de datos ordenada que permite elementos repetidos. Los elementos de una tupla no se pueden modificar. En python se representan con paréntesis y separadas por coma, es decir:

In [1]:
# Tupla de enteros
(1,2,3,4,5)

(1, 2, 3, 4, 5)

In [2]:
# Tambien es posible realizar tuplas con diferentes tipos de datos
(1,'2',3,4.05,True)

(1, '2', 3, 4.05, True)

In [4]:
# Se pueden combinar diferentes tipos de tuplas dentro de una misma
((1,2),('a','b','c'))

((1, 2), ('a', 'b', 'c'))

In [9]:
# Si sumamos tuplas, las concatenamos
(1,2,3,4,5) + (6,7,8,9,10)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

## Listas

Las listas son estructuras de datos ordenadas y permiten valores duplicados. Los elementos de una lista están indexados y comienzan en 0. Las representamos con corchetes y separadas por coma. También es posible declarar una lista a partir de list().

In [5]:
# Lista de enteros
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [6]:
# Lista con diferentes tipos de datos
['a','b','c',9.02,10.34]

['a', 'b', 'c', 9.02, 10.34]

In [7]:
# Lista que contiene listas como elementos
[[1,2],['a','b']]

[[1, 2], ['a', 'b']]

In [16]:
# Concatenar dos listas diferentes
['a','b'] + ['c']

['a', 'b', 'c']

In [42]:
lista = ['a','b','c']

In [43]:
# Acceder a un elemento de la lista
lista[0]

'a'

In [44]:
# Contar los elementos de una lista
len(lista)

3

In [45]:
# Sumar los elementos de una lista
sum([1,2,3,4,5])

15

In [50]:
# Agregar al final un elemento a una lista
lista.append('d')
lista

['a', 'b', 'c', 'd']

In [51]:
# Acceder a varios elementos de la lista al mismo tiempo
lista[:3] # :n denota desde la posicion 0 a la posicion n-1

['a', 'b', 'c']

In [47]:
# Ultimo elemento de la lista
lista[-1]

'd'

In [48]:
# Modificar un elemento de una lista
lista[3] = 'z'
lista

['a', 'b', 'c', 'z']

In [49]:
# Eliminar un elemento de una lista (siempre el que se encuentre lo antes posible)
lista.remove('z')
lista

['a', 'b', 'c']

## Conjuntos

Los conjuntos en Python son estructuras desordenadas que no admiten repetición de elementos ni están indexadas. Estas estructuras se definen mediante set() o {}

In [18]:
set([1,2,3]) == {1,2,3}

True

In [19]:
conjunto_par = set([0,2,4,6,8])
conjunto_impar = set([1,3,5,7,9])
conjunto_par_red = set([0,2])
conjunto_par

{0, 2, 4, 6, 8}

### Operaciones con conjuntos

In [20]:
# Longitud de un conjunto
len(conjunto_par)

5

In [22]:
# Union de dos conjuntos
conjunto_par | conjunto_impar

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [23]:
# Interseccion de dos conjuntos
conjunto_par & conjunto_impar

set()

In [24]:
# Interseccion no vacía de dos conjuntos
conjunto_par & conjunto_par_red

{0, 2}

## Diccionarios

Los diccionarios son una estructura ordenada con elementos indexados y sus elementos (valores) son modificables. No puede haber elementos con clave repetida. La principal diferencia con una lista es que el indice de los elementos se define mediante una clave. Los diccionarios los definimos mediante {} (especificando la clave y el valor con la estructura clave:valor) o con la expresión dict()

In [25]:
dict(primer_examen = 8, segundo_examen=5 , tercer_examen = 6) == {'primer_examen':8, 'segundo_examen':5, 'tercer_examen' : 6}

True

In [3]:
diccionario = {'primer_examen':8, 'segundo_examen':5, 'tercer_examen' : 6}
diccionario

{'primer_examen': 8, 'segundo_examen': 5, 'tercer_examen': 6}

In [4]:
# Agregar elementos a un diccionario
diccionario['cuarto_examen'] = 9
diccionario

{'primer_examen': 8,
 'segundo_examen': 5,
 'tercer_examen': 6,
 'cuarto_examen': 9}

In [5]:
# Acceder a elementos del diccionario
diccionario["segundo_examen"]

5

In [6]:
# Acceder a las claves del diccionario
diccionario.keys()

dict_keys(['primer_examen', 'segundo_examen', 'tercer_examen', 'cuarto_examen'])

In [7]:
# Acceder a los valores del diccionario
diccionario.values()

dict_values([8, 5, 6, 9])

In [8]:
# Acceder a las tuplas clave valor del diccionario
diccionario.items()

dict_items([('primer_examen', 8), ('segundo_examen', 5), ('tercer_examen', 6), ('cuarto_examen', 9)])

In [32]:
# Actualizar un valor del diccionario
diccionario["tercer_examen"] = 7

In [9]:
# Concatenar dos diccionarios
diccionario_act = dict(primer_examen = 2, quinto_examen = 5, sexto_examen = 7)

diccionario.update(diccionario_act)
diccionario

{'primer_examen': 2,
 'segundo_examen': 5,
 'tercer_examen': 6,
 'cuarto_examen': 9,
 'quinto_examen': 5,
 'sexto_examen': 7}

## Arrays

Una de las estructuras más necesarias fuera del ecosistema base de Python son los arrays definidos en la librería NumPy. Estos arrays tienen características de vector en el sentido matemático (permiten operaciones componente a componente). Además son elementos que están indexados y permiten la repetición de elementos.

In [34]:
import numpy as np

In [38]:
# Crear un array de np
array = np.array([1,2,3])
array

array([1, 2, 3])

In [36]:
# Crear un array de ceros
np.zeros(3)

array([0., 0., 0.])

In [37]:
# Crear un array de unos
np.ones(3)

array([1., 1., 1.])

In [39]:
# Acceder a una posicion de un array
array[0]

1

In [52]:
# Acceder a varias posiciones del array
array[1:3]

array([2, 3])

### Operaciones con arrays

In [81]:
# Suma de arrays
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [82]:
# Resta de arrays
np.array([4,5,6]) - np.array([1,2,3])

array([3, 3, 3])

In [83]:
# Constante por una array
5 * np.array([1,2,3])

array([ 5, 10, 15])

In [84]:
# Multiplicacion de arrays
np.array([1,2,3]) * np.array([4,5,6])

array([ 4, 10, 18])

In [95]:
# División de arrays
np.array([1,2,3]) / np.array([4,5,6])

array([0.25, 0.4 , 0.5 ])

In [89]:
# Array unidimensional (filas)
np.array([1,2,3]).ndim

1

In [90]:
# Array dos dimensional (filas)
np.array([[1,2,3],[4,5,6]]).ndim

2

In [92]:
# Dimensiones del array (fila,columna)
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [94]:
# Transponer un array
np.array([[1,2,3],[4,5,6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

Existen muchas funciones y alternativas que se proporcionan a través de arrays de numpy, asi como construcción de matrices y productos entre ellas. Para ver más funciones y opciones que se pueden aplicar os dejo un enlace con la documentación: https://numpy.org/

## Condicionales

Los condicionales son expresiones que hacen que se ejecute una acción a partir de una o más condiciones dadas. En python usamos las expresiones if, else e ifelse.

In [62]:
lista = list(range(21)) # Crear una lista con los números del 0 al 20
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [64]:
# Si la suma de la lista es par devuelve 0 si es impar devuelve 1
if (sum(lista) % 2) == 0:
    print('La suma de los elementos de la lista es un número par')
else:
    print('La suma de los elementos de la lista es un número impar')

La suma de los elementos de la lista es un número par


In [65]:
# Anidar más condiciones

if (sum(lista) % 2 == 0) & (sum(lista) % 3 == 0):
    print('La suma de los elementos de la lista es divisible por 6')
else:
    print('La suma de los elementos de la lista no es divisible por 6')

La suma de los elementos de la lista es divisible por 6


In [66]:
# Verificar condiciones de manera secuencial

if sum(lista) > 250:
    print("La suma de los 20 primeros números es mayor que 250")
elif (200 < sum(lista)) & (sum(lista) < 250):
    print("La suma de los 20 primeros números es mayor que 200 pero menor que 250")
else:
    print("La suma de los 20 primeros números es menor que 200")

La suma de los 20 primeros números es mayor que 200 pero menor que 250


## Bucles for y while

Los bucles for y while son expresiones iterativas que intentan recorrer estructuras de datos aplicando las acciones que se pretendan durante el proceso. Las tuplas, listas, conjuntos, diccionarios y arrays son estructuras *iterables*,es decir, podemos recorrerlas secuencialmente.

In [68]:
# De la lista anterior voy a sumar únicamente los números pares.
suma = 0
for n in lista:
    if n % 2 == 0:
        suma += n # Esto es equivalente a ---> suma = suma + n

print('La suma de los pares de la lista anterior es: {}'.format(suma))

La suma de los pares de la lista anterior es: 110


In [70]:
# Sin necesidad de la lista anterior, podemos realizar el mismo proceso con un bucle while (CUIDADO CON LOS BUCLES INFINITOS)
suma = 0
n = 0
while n <= 20:
    if n % 2 == 0:
        suma += n
    n += 1

print('La suma utilizando el bucle while es: {}'.format(suma))

La suma utilizando el bucle while es: 110


### Formas de salir de un bucle

Existen tres maneras de salir de un bucle, a partir de los comandos pass, continue y break.

* Pass indica una ejecución nula de la iteración.
* Continue ejecuta el final de esa iteración pero el bucle continua
* Break termina por completo el bucle

In [78]:
n = 0
while n < 10:
    n += 1
    if n == 5:
        pass    
    print("El valor de n es: {}".format(n))

El valor de n es: 1
El valor de n es: 2
El valor de n es: 3
El valor de n es: 4
El valor de n es: 5
El valor de n es: 6
El valor de n es: 7
El valor de n es: 8
El valor de n es: 9
El valor de n es: 10


In [79]:
n = 0
while n < 10:
    n += 1
    if n == 5:
        continue
        
    print("El valor de n es: {}".format(n))

El valor de n es: 1
El valor de n es: 2
El valor de n es: 3
El valor de n es: 4
El valor de n es: 6
El valor de n es: 7
El valor de n es: 8
El valor de n es: 9
El valor de n es: 10


In [80]:
n = 0
while n <= 10:
    n += 1
    if n == 5:
        break
        
    print("El valor de n es: {}".format(n))

El valor de n es: 1
El valor de n es: 2
El valor de n es: 3
El valor de n es: 4
